### ISSUE TITLE
How to generate the dataset?

### ISSUE THREAD

**Issue by solomon-ma** [jayLEE0301/snerl_official#3]
Thanks for your wonderful work.

I am a beginner in Reinforcement Learning.
Could you tell me how to generate the environment? For your case, Do I really need to find a soccer, drawer, or hammer to generate your environment?
But these data are not in the popular NeRF dataset, Could you provide it?

**Comment by jayLEE0301** [comment]
we utilized the Metaworld environment (https://github.com/Farama-Foundation/Metaworld)

To generate the dataset, we first located cameras in the environment by modifying the original code of Metaworld
To see how we generated cameras in a .xml file, please refer to the issue below.
(https://github.com/jayLEE0301/snerl_official/issues/1)

We do have plans to provide the dataset someday, but there is no set schedule for when we could provide it.

**Comment by sucy171106** [comment]
I'm still waiting for your datasets.
![image](https://github.com/jayLEE0301/snerl_official/assets/73210278/64f79aeb-5331-4303-895f-9f08b65a0290)

**Comment by jayLEE0301** [comment]
We apologize for the delay in delivering the dataset.

We hope to have a dataset for one of the environments up within 7 days.

**Comment by jayLEE0301** [comment]
We have released the drawer and soccer dataset. If there are any issues with the dataset, please inquire. We apologize for the delayed release.
