### ISSUE TITLE
about datasets

### ISSUE THREAD

**Issue by freor** [jayLEE0301/snerl_official#4]
Hi, thank you for publishing your code.
I'm trying to making dataset for SNeRL,
**but training with my dataset does not make depth map very well.**
and it seems to overfit to each view images.
so, I'm asking you some parts of the dataset!!

as I understand,
for **'cam_1_1'**, **'camera_matrix'** should be **'pose_spherical(18-180, -(90-27), 4.)'**
which 18 is for euler_x of cam_1_1, and 27 is for euler_y of cam_1_1.
and **'camera_angle_x'** is **'1.57...'** which is **'90 * 3.14 / 180'** because camera's fovy you set is 90 degree.

is this right dataset specification?

**Comment by jayLEE0301** [comment]
https://github.com/jayLEE0301/snerl_official/issues/1#issuecomment-1567787941

Please check this closed issue.
Thank you for having interests about our work.
