### ISSUE TITLE
Question about Train Donstream RL

### ISSUE THREAD

**Issue by Greatsjk** [jayLEE0301/snerl_official#6]
Thank you for your wonderful code.
I finished the Pretrain Encoder and tried to train RL policy. However,  I encountered the following problem：
`Exception: Failed to load XML file: .../snerl_official/metaworld/.metaworld/envs/assets_v2/sawyer_xyz/sawyer_drawer.xml. mj_loadxML error: b"Error: PNG file load error 'empty input or file doesn't exist' in texture id = 1nobiect name = T table, id 1. line = 9. column = 9"`
I guess that this is because of the lack of `<texture name="T_table" type="cube" file="../textures/wood2.png"/>` in [basic_scene.xml](https://github.com/jayLEE0301/snerl_official/blob/main/metaworld/metaworld/envs/assets_v2/scene/basic_scene.xml). I have no idea about finding or generating the image.
Could you please help me to solve the problems?

**Comment by jonyzhang2023** [comment]
same question @jayLEE0301 @Greatsjk @dsshim0125

**Comment by jayLEE0301** [comment]
Fixed! thank you for reporting issue :)
